"use client";
import { useState } from "react";
import { useLocale } from "next-intl";
import { Trash2 } from "lucide-react";
import type { Editor } from "@tiptap/react";
import type { Node as PMNode } from "@tiptap/pm/model";
import { closeHistory } from "@tiptap/pm/history";
import { pageContentRange, pageTables } from "@/lib/editor/delete-page";
export function DeletePageButton({editor,current,total,locked}:{editor:Editor;current:number;total:number;locked:boolean}) {
  const en=useLocale()==="en";const [selection,setSelection]=useState<{from:number;to:number;page:number;doc:PMNode}|null>(null);const [error,setError]=useState("");
  function prepare(){const range=pageContentRange(editor.view,current,total);if(!range){setError(en?"This page has no removable content.":"Questa pagina non contiene contenuti da eliminare.");return;}setError("");setSelection({...range,page:current,doc:editor.state.doc});}
  function remove(range?:{from:number;to:number}){if(!selection||locked)return;if(!selection.doc.eq(editor.state.doc)){setSelection(null);setError(en?"The document changed. Select the page again.":"Il documento è cambiato. Seleziona nuovamente la pagina.");return;}const tr=closeHistory(editor.state.tr).delete(range?.from??selection.from,range?.to??selection.to);if(tr.doc.eq(editor.state.doc)){setError(en?"Page deletion cannot remove this table structure. Use Delete entire table below if it is the old contents.":"La cancellazione della pagina non rimuove questa struttura. Usa Elimina intera tabella qui sotto se contiene il vecchio indice.");return;}editor.view.dispatch(tr);setError("");setSelection(null);}
  return <><button type="button" className="delete-page-button" disabled={locked} onClick={prepare} aria-label={en?"Delete current page":"Elimina pagina corrente"} title={en?"Delete current page":"Elimina pagina corrente"}><Trash2 size={15}/></button>{error&&<span role="alert" className="delete-page-error" onClick={()=>setError("")}>{error}</span>}{selection&&<div className="studio-modal-backdrop"><section className="studio-modal hexclave-private" role="dialog" aria-modal="true" aria-labelledby="delete-page-title"><h2 id="delete-page-title">{en?`Delete page ${selection.page}?`:`Eliminare pagina ${selection.page}?`}</h2><p>{en?`This removes the content on this editor page (${selection.doc.textBetween(selection.from,selection.to," ").length} text characters), including any selected images.`:`Rimuove il contenuto di questa pagina dell’editor (${selection.doc.textBetween(selection.from,selection.to," ").length} caratteri di testo), comprese eventuali immagini selezionate.`}</p><p>{en?"Following pages will reflow. You can reverse this with Undo.":"Le pagine successive si ricomporranno. Puoi ripristinare il contenuto con Annulla nell’editor."}</p>{pageTables(selection.doc,selection).map((table,index)=><div className="title-plan-notice" key={table.from}><p>{en?`This page intersects table ${index+1} (${table.characters} characters). If this is the old contents, you can remove the entire table, including its content on other pages. Following chapters will be preserved.`:`Questa pagina attraversa la tabella ${index+1} (${table.characters} caratteri). Se è il vecchio indice, puoi eliminare la tabella intera, compreso il contenuto sulle altre pagine. I capitoli successivi vengono preservati.`}</p><button className="studio-button" disabled={locked} onClick={()=>remove(table)}>{en?"Delete entire table":"Elimina intera tabella"}</button></div>)}{error&&<p role="alert">{error}</p>}<div className="modal-actions"><button autoFocus className="studio-button" onClick={()=>setSelection(null)}>{en?"Cancel":"Annulla"}</button><button className="studio-button primary" disabled={locked} onClick={()=>remove()}>{en?"Delete page":"Elimina pagina"}</button></div></section></div>}</>;
}
