"use client";
import { useRef, useState } from "react";
import { useLocale } from "next-intl";
import type { Editor } from "@tiptap/react";
import { BookOpenCheck, Check, ChevronRight } from "lucide-react";
import { detectReferences, type ReferenceReport } from "@/lib/editor/references";
export function ReferencesPanel({editor,locked,onNavigate,report}:{report:ReferenceReport;editor:Editor;locked:boolean;onNavigate:(pos:number)=>void}) {
  const en=useLocale()==="en";const [confirm,setConfirm]=useState(false);
  const [filter,setFilter]=useState("all");
  const passages=useRef<HTMLDetailsElement>(null);
  const labels:Record<string,string>={all:en?"All passages":"Tutti i passaggi",citation:en?"References":"Richiami",bibliography:en?"Bibliography entries":"Voci bibliografiche",quote:en?"Possible quotations":"Possibili citazioni",source:en?"Sources / notes":"Fonti / note"};
  function show(kind:string){setFilter(kind);if(passages.current){passages.current.open=true;const summary=passages.current.querySelector("summary");summary?.focus({preventScroll:true});passages.current.scrollIntoView({block:"nearest",behavior:"instant"});}}
  const visible=report.items.filter(item=>filter==="all"||item.kind===filter||(filter==="quote"&&item.kind==="attribution")||(filter==="source"&&item.kind==="note"));
  const count=(kind:string)=>report.items.filter(i=>(i.kind===kind||(kind==="quote"&&i.kind==="attribution"))).length;
  const reasons={attribution:en?"Claim attributed to a source: add a precise passage reference and verify that it supports the claim. It has not been fact-checked.":"Affermazione attribuita a una fonte: indica il passaggio preciso e verifica che sostenga quanto scritto. L’affermazione non è verificata.",ambiguous:en?"Multiple matching entries: verify the intended source.":"Più voci corrispondenti: verifica quale fonte è quella corretta.",unmatched:en?"No matching entry found — check whether this is a reference or a note.":"Nessuna voce corrispondente trovata: verifica se è un riferimento o una nota.",duplicate:en?"Possible duplicate entry.":"Possibile voce duplicata.",incomplete:en?"No date or source identifier detected. Check completeness.":"Non ho riconosciuto una data o un identificativo della fonte. Verifica la completezza.",mixed:en?"Numbered and unnumbered entries: check the convention.":"Voci numerate e non numerate: verifica la convenzione."};
  function insert(){
    if(locked)return;
    const fresh=detectReferences(editor.state.doc);if(fresh.bibliographyFound||!fresh.draft.length){setConfirm(false);return;}
    editor.chain().focus().insertContentAt(editor.state.doc.content.size,[{type:"heading",attrs:{level:1},content:[{type:"text",text:en?"Sources to complete":"Fonti da completare"}]},...fresh.draft.map(text=>({type:"paragraph",content:[{type:"text",text}]}))]).run();setConfirm(false);
  }
  return <details open className="references-panel hexclave-private"><summary><BookOpenCheck size={16}/>{en?"Citations and sources":"Citazioni e fonti"}</summary>
    <p className="reference-status"><Check size={14}/>{en?"Automatic local check":"Controllo locale automatico"}</p>
    <div className="reference-counts">{["citation","bibliography","quote","source"].map(kind=><button type="button" key={kind} aria-pressed={filter===kind} onClick={()=>show(kind)} disabled={(count(kind)+(kind==="source"?count("note"):0))===0}><strong>{count(kind)+(kind==="source"?count("note"):0)}</strong>{labels[kind]}<ChevronRight size={13}/></button>)}</div>
    <p className="modal-note">{en?"Detects common numeric and author–year references, quotation blocks, discursive attributions, URLs and DOIs. Sources have not been externally verified. Imported notes may appear as ordinary text.":"Riconosce richiami numerici e autore–anno comuni, blocchi citati, attribuzioni discorsive, URL e DOI. Le fonti non sono verificate esternamente. Le note importate possono apparire come testo normale."}</p>
    <p>{report.bibliographyFound?(en?"Existing bibliography preserved.":"Bibliografia esistente preservata."):(en?"No bibliography section detected.":"Nessuna sezione bibliografica riconosciuta.")}</p>
    {report.issues.length>0?<details open><summary>{en?"To check":"Da verificare"} · {report.issues.length}</summary>{report.issues.map(issue=><article className="reference-issue" key={issue.id}><p>{reasons[issue.code]}</p>{issue.text&&<p className="reference-excerpt">{issue.text}</p>}<button className="structure-reference" onClick={()=>onNavigate(issue.pos)}>{en?"Go to passage":"Vai al passaggio"}<ChevronRight size={13}/></button>{issue.related.map(pos=><button key={pos} className="structure-reference" onClick={()=>onNavigate(pos)}>{en?"Compare entry":"Confronta voce"}</button>)}</article>)}</details>:<p className="modal-note">{en?"No anomalies detected by these checks; this is not a completeness certification.":"Nessuna anomalia rilevata da questi controlli; non è una certificazione di completezza."}</p>}
    {report.items.length>0&&<details ref={passages}><summary tabIndex={0}>{labels[filter]} · {visible.length}</summary><label className="reference-filter">{en?"Show":"Mostra"}<select value={filter} onChange={event=>setFilter(event.target.value)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{visible.length===0&&<p>{en?"No passages in this category.":"Nessun passaggio in questa categoria."}</p>}{visible.map(item=><div className="reference-issue" key={item.id}>{item.attribution&&<p><strong>{en?"Attribution to document":"Attribuzione da documentare"}</strong><br/>{item.attribution.author}{item.attribution.work&&<> · <em>{item.attribution.work}</em></>}{item.attribution.locator&&<> · {item.attribution.locator}</>}</p>}<button className="structure-reference reference-excerpt" onClick={()=>onNavigate(item.pos)}><small>{en?"Go to passage":"Vai al passaggio"} →</small>{item.text}</button>{item.targets.map(pos=><button key={pos} className="structure-reference" onClick={()=>onNavigate(pos)}>{en?"Open linked entry":"Apri voce collegata"}</button>)}</div>)}</details>}
    {report.draft.length>0&&<div className="reference-draft"><p>{en?"A sources list can be prepared from the URLs, DOIs and explicit author/work references already in the manuscript. Missing bibliographic details will not be invented.":"Posso preparare un elenco dagli URL, DOI e riferimenti espliciti ad autori/opere già presenti nel manoscritto. I dati bibliografici mancanti non saranno inventati."}</p><button className="studio-button secondary full" disabled={locked} onClick={()=>setConfirm(!confirm)}>{en?"Preview sources draft":"Anteprima bozza delle fonti"}</button>{confirm&&<><ul>{report.draft.map(text=><li key={text}>{text}</li>)}</ul><p>{en?"Append this list to the manuscript? It will need completion. You can undo this action.":"Aggiungere l’elenco in fondo al manoscritto? Sarà da completare. Puoi annullare l’operazione."}</p><button className="studio-button primary" disabled={locked} onClick={insert}>{en?"Approve and insert":"Approva e inserisci"}</button><button className="studio-button" onClick={()=>setConfirm(false)}>{en?"Cancel":"Annulla"}</button></>}</div>}
  </details>;
}
