"use client";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from "@hexclave/ui";
import { Settings, X } from "lucide-react";
import { useLocale } from "next-intl";
import type { ManuscriptProject } from "@/lib/editor/types";
export function PreferencesModal({projects,onClose}:{projects:ManuscriptProject[];onClose:()=>void}) {
  const en=useLocale()==="en";
  const analysis=projects.reduce((sum,p)=>sum+(p.analysis?.costUsd??p.review?.cost??0),0);
  const titles=projects.reduce((sum,p)=>sum+(p.titlePlan?.cost??0),0);
  const usd=(value:number)=>new Intl.NumberFormat(en?"en-US":"it-IT",{style:"currency",currency:"USD",minimumFractionDigits:4}).format(value);
  return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent noCloseButton className="bookr-account-modal hexclave-private" style={{height:"auto",maxWidth:600}}><header className="account-modal-header"><Settings size={22}/><div><DialogTitle>{en?"User preferences":"Preferenze utente"}</DialogTitle><DialogDescription>{en?"AI usage":"Consumi AI"}</DialogDescription></div><DialogClose className="account-modal-close" aria-label={en?"Close":"Chiudi"}><X size={20}/></DialogClose></header><section className="p-7 space-y-5"><h2 className="text-lg font-semibold">{en?"Usage and costs":"Consumi e costi"}</h2><dl className="space-y-4"><div className="flex justify-between"><dt>{en?"Latest manuscript analyses":"Ultime analisi dei manoscritti"}</dt><dd>{usd(analysis)}</dd></div><div className="flex justify-between"><dt>{en?"Latest heading proposals":"Ultime proposte di titoli"}</dt><dd>{usd(titles)}</dd></div><div className="flex justify-between border-t pt-4 font-semibold"><dt>{en?"Recorded total":"Totale registrato"}</dt><dd>{usd(analysis+titles)}</dd></div></dl><p className="text-sm text-ink/60">{en?"Based on the latest analyses saved on this device, including trashed books. This is not a billing statement or a complete usage history. Interrupted requests may include an estimated reserve.":"Basato sulle ultime analisi salvate su questo dispositivo, inclusi i libri nel cestino. Non è un estratto conto né uno storico completo dei consumi. Le richieste interrotte possono includere una riserva stimata."}</p><p className="text-sm text-ink/60">{en?"Service limits are managed automatically by Bookr.":"I limiti di servizio sono gestiti automaticamente da Bookr."}</p></section></DialogContent></Dialog>;
}
